dist: trusty
language: python
sudo: false

branches:
  only:
  - master

python:
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt

script:
  - ./setup.py test
  - ./run_integration_tests.py
